### PR TITLE
Need to fix the negative number intake

### PR DESCRIPTION
**Pull request by sinaru**
Your code is ignoring the negative positions. So I have modifiedl the JavaScript file current regular expression to match negative numbers. Just enocuntered this issue when I was refferring locations in negative longitudes (such as in USA).
Hope my regular expression fix is correct, it worked for me. : )

### CODE REVIEW

**Comment by Kolyunya** [comment]
@sinaru thank you very much for your contribution. I've fixed the error and made my own commit since the `?` sign is excessive in that regular expression.

**Comment by Kolyunya** [comment]
@sinaru the fix is available in the [patch 1.0.2](https://github.com/Kolyunya/yii2-map-input-widget/releases/tag/1.0.2).

**Comment by sinaru** [comment]
@Kolyunya So you end up using my change ^^. Just wondered what you changed since you said that you have corrected the regular expression a little.

**Comment by Kolyunya** [comment]
@sinaru in fact I did not end up using you change. Note that in your patch the `-?` token is in square braces and `[-?\d.]+` matches any sequence consisting from any number of `-`, `?` or `.` symbols or any digit. That means that this pattern will match even `?-0-1-2.?-3-4?` string. This does not make much sense, does it?
But in my patch the `-?` is located outside the square braces and means a single and optional instance of the `-`.
Please correct me if I'm mistaking somehow.

**Comment by sinaru** [comment]
Hi my bad. I didnt see where you have put the ? 
I was just trying to find a fix and found ? is used to indicate optional value. Still learning regular expressions. :jack_o_lantern: 

It was working ok since the string provided would contain a proper decimal numbers, but you are right it will also match if it contains ? also. Then again current regular expression would also match "-45.6.9". Maybe should put the (.) dot outside the square brackets?
ex: /-?[\d]+.[\d]+/g

https://jsfiddle.net/qr400dqt/

**Comment by Kolyunya** [comment]
@sinaru your regular expression is not gonna work as you expect for integer values e. g. `42`. The dot and the fractional part should be optional. 

Also the `.` is not the dot: it's a special character meaning `any character`. The dot is represented by the `\.` in regular expressions. 

The final expression should be something like `-?\d+(\.\d+)?`. I'm gonna make a patch soon.

**Comment by Kolyunya** [comment]
@sinaru done in [patch 1.0.3](https://github.com/Kolyunya/yii2-map-input-widget/releases/tag/1.0.3).

**Pull request closed without merging**
